name: CI

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Run checks and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Wordle Check and test
        run: |
          cd wordle-game
          cargo fmt --all --check
          cargo b -r

      - name: Session Check and test
        run: |
          cd session-proxy
          cargo fmt --all --check
          cargo b -r
          
